Array

In [12]:
import numpy as np
a=np.array([5,6,6])

print(a)
print(type(a))

[5 6 6]
<class 'numpy.ndarray'>


In [14]:
import numpy as np
a=np.array([5,6,6])
a

array([5, 6, 6])

In [16]:
import numpy as np
a=[4,3,6,8]
b=np.array(a)
print(b)
print(b.ndim)

[4 3 6 8]
1


In [22]:
l=[]
for i in range(1,5):
    int_1=int(input("enter:"))
    l.append(int_1)
print(np.array(l))

enter: 1
enter: 23
enter: 2
enter: 3


[ 1 23  2  3]


In [24]:
arr=np.array([[1,3,4,5],[4,5,6,7],[7,0,9,8]])
print(arr)
print(arr.ndim)

[[1 3 4 5]
 [4 5 6 7]
 [7 0 9 8]]
2


In [26]:
arr=np.array([1,2,3,4], ndmin=10)
print(arr)
print(arr.ndim)

[[[[[[[[[[1 2 3 4]]]]]]]]]]
10


Random


 Rand()

In [42]:
import numpy as np
var= np.random.rand(4)
print(var)


[0.32765415 0.52138552 0.67708283 0.69348548]


In [40]:
var1= np.random.rand(2,5)
print(var1)

[[0.89605245 0.60727753 0.270534   0.41244975 0.34148069]
 [0.10563066 0.24759911 0.16094842 0.76798774 0.59050491]]


randn()

In [45]:
var2= np.random.randn(5)
print(var2)

[-0.70880212  1.11718977 -1.6442842   1.12306217 -0.84606876]


In [47]:
var3=np.random.randn(2,5)
print(var3)

[[-1.90442312 -1.68346214  1.1338975   1.53570696  1.823386  ]
 [ 0.08898704 -2.06922613  0.50199216  1.27711702  0.33978113]]


ranf()


In [50]:
var4= np.random.ranf(4)
print(var4)

[0.61709833 0.87841968 0.60448208 0.4123117 ]


randint()

In [53]:
var5= np.random.randint(5,20,5) #randint(min,max,totalvalue)
print(var5)

[17 13 15  7 11]


Data Type

In [4]:
import numpy as np
var= np.array([1,2,3,4])
print("Data type :", var.dtype)

Data type : int32


In [6]:
var= np.array([1.2,3.4,2.4])
print("Data type :", var.dtype)

Data type : float64


In [8]:
var= np.array(["o","i","u"])
print("Data type :", var.dtype)

Data type : <U1


In [10]:
var= np.array([1,2,3,4,"u","o","i"])
print("Data type :", var.dtype)

Data type : <U11


In [20]:
x=np.array([1,3,4,5],dtype=np.float64)
print("Data type :", x.dtype)
print(x)

Data type : float64
[1. 3. 4. 5.]


In [18]:
x1=np.array([1,3,4,5],dtype="f")
print("Data type :", x1.dtype)
print(x1)

Data type : float32
[1. 3. 4. 5.]


In [30]:
x=np.array([1,3,4,5],dtype=np.int32)
print("Data type :", x.dtype)
print(x)

Data type : int32
[1 3 4 5]


In [ ]:
x2=np.array([1,3,4,5])



print("Data type :", x2.dtype)
print(x2)